name: Build and Release with jlinkZip

on:
  push:
    tags:
      - 'v*'  # Triggers only when a tag starting with 'v' is pushed (e.g., v1.0, v2.0.1, etc.)

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permissions for gradlew
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build with jlinkZip
        run: ./gradlew jlinkZip

      - name: Archive build artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: jlink-zip-${{ matrix.os }}
          path: app/build/image.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: jlink-zip-${{ matrix.os }}
          path: release_artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release_artifacts/*.zip
          asset_name: jlink-zip-${{ matrix.os }}-${{ github.ref_name }}.zip
          asset_content_type: application/zip
